repo: jsdelivr
owner: jsdelivr

user: jsdelivrbot
auth_token: # token
post_secret: # secret

merge_re: hey merge in (\d+) 

path_to_repo: ~\jsdelivr

# Users to auto merge prs from
trusted_users:
    - jsdelivrbot