repo: jsdelivr
owner: jsdelivr

user: jsdelivrbot
auth_token: # secret
post_secret: # secret

merge_re: "@jsdelivrbot (.* )?squ[ia]sh.*"

# For squash&merging
path_to_repo: /home/jsdelivr/
repo_branch: master
repo_remote: origin

# Users to auto merge prs from
trusted_users:
  - jsdelivrbot

# how often to recheck unvalidated packages
recheck_interval: 2 hour